<?php

namespace PhpMg\Octopus\Tests\Language;

use PhpMg\Octopus\Language\PortugueseLanguage;
use PHPUnit_Framework_TestCase;

class PortugueseLanguageTest extends PHPUnit_Framework_TestCase
{
    public function assertPreConditions()
    {
        $this->assertTrue(class_exists(PortugueseLanguage::class));
        parent::assertPreConditions(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function twoShouldReturnDois()
    {
        $language = new PortugueseLanguage();
        $this->assertEquals('dois', $language->getValueInWords(2));
    }

    /**
     * @test
     */
    public function tenShouldReturnDez()
    {
        $language = new PortugueseLanguage();
        $this->assertEquals('dez', $language->getValueInWords(10));
    }
}
